"""update_centros_treinamento

Revision ID: 2cc4600df42c
Revises: 0674c87ed9ad
Create Date: 2024-05-02 16:09:51.823498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc4600df42c'
down_revision: Union[str, None] = '0674c87ed9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('proprietario', sa.String(length=30), nullable=False))
    op.drop_column('centros_treinamento', 'propprietario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('propprietario', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('centros_treinamento', 'proprietario')
    # ### end Alembic commands ###
